services:
  perfma-gpt:
    image: my-next-app
    container_name: my-next-app
    environment:
      - MY_NEXT_APP=1
    ports:
      - "42800:42800"
      - "42900:42900"
    volumes:
      - ./:/root/my-next-app
    command: npm run start
    restart: unless-stopped
