services:
  perfma-gpt:
    image: my-next-app
    container_name: my-next-app
    environment:
      - JIMAO=1
    ports:
      - "42800-43000:42800-43000"
    volumes:
      - ./:/root/my-next-app
    command: npm run start
    restart: unless-stopped
