services:
  my-next-app:
    image: my-next-app
    container_name: my-next-app
    environment:
      - MY_NEXT_APP=1
    ports:
      - "42800:42800"
    volumes:
      - ../:/root/my-next-app
    command: npm run start
    restart: "unless-stopped"
  my-next-app-dev:
    image: my-next-app
    container_name: my-next-app-dev
    environment:
      - MY_NEXT_APP=1
    ports:
      - "42900:42900"
    volumes:
      - ../:/root/my-next-app
    command: npm run dev
    restart: "unless-stopped"
  my-next-app-install:
    image: my-next-app
    container_name: my-next-app-install
    volumes:
      - ../:/root/my-next-app
    command: npm install
    restart: "no"
  my-next-app-build:
    image: my-next-app
    container_name: my-next-app-build
    volumes:
      - ../:/root/my-next-app
    command: npm run build
    restart: "no"
  my-next-app-start:
    image: my-next-app
    container_name: my-next-app-start
    ports:
      - "42800:42800"
    volumes:
      - ../:/root/my-next-app
    command: npm run start
    restart: "no"
